### ISSUE TITLE
nothing deconvolved when using a very high-res image

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/PyMORESANE#10]
OK, totally different MS, different problem. This contains a very bright, barely resolved (i.e. barely larger than a point) source. I made a highly oversampled image, thinking I could deconvolve at least some of the structure. However, MORESANE returns a zero model -- I would have expected it to fit at least something. From the log it looks like all scales from 0 to 10 fail, after which it gives up. But I did ask it to look at much higher scales (-sps 500), so not sure why it doesn't try, 

MS is in `/net/aretha/home/oms/VLA-3C147/MS-Jon`

Command was:

`/home/oms/src/wsclean-code/wsclean/build/wsclean -niter 3 -scale 6.94444444444e-06 -name B147-LO-NOIFS-NOPOL-4M5S-spw0-s1-wsclean -weight briggs 0.00 -moresane-arg '-aog -sbr 640 -sps 500 -sl 3' -channelrange 0 64 -datacolumn CORRECTED_DATA -field 0 -pol I -gain 0.05 -moresane-ext /home/oms/PyMORESANE/pymoresane/bin/runsane -threshold 0 -nosmallinversion -size 1024 1024 -mgain 0.85 B147-LO-NOIFS-NOPOL-4M5S.MS`

**Comment by JSKenyon** [comment]
I will have a look but "-sps" is not what you need to specify to change the scale count. That option only works in the deprecated single run mode. "-sc" will work, but the number of wavelet scales is capped based on the size of the image. I think I use log2(N)-1 where N is the number of pixels per side in the dirty image. This is to prevent filter wraparound at the high scales. However, that should not be preventing PyMORESANE from giving an answer. I will follow this up.

**Comment by JSKenyon** [comment]
Ah, this is actually great. This has exposed a bug which I would otherwise have missed. The parameters with which I was initialising the convergence criteria were preventing the algorithm from ever accepting a step. I have fixed it and I doing some quick tests. I believe that the results from this may still be a little odd because the source is so bright. Will finish up testing then commit.

**Comment by JSKenyon** [comment]
Ok, should be fixed in v0.3.4. Closing for now.
