### ISSUE TITLE
Convolution issue

### ISSUE THREAD

**Issue by cyriltasse** [ratt-ru/PyMORESANE#18]
So as far as I can see PyMoresane cannot handle psf and dirties with different sizes. While in principle for the convolution problem to be fully posed the psf size should be at least twice as big as the dirty's. Is there a good reason for that? I guess since you're working on large images, your psf is in general large enough so that the power goes to zero toward the edges. However, this is not the case anymore for SSD where we work on small islands, and that would break also in snapshot mode (maybe the tart project is in that regime)... Any comment on this?

**Comment by JSKenyon** [comment]
It does have support for using a double size PSF. It doesn't support arbitrary sizes. That poses problems for the GPU kernels if I recall.

**Comment by cyriltasse** [comment]
ok thanks!
