### ISSUE TITLE
Cuda.init() error

### ISSUE THREAD

**Issue by rammanouil** [ratt-ru/PyMORESANE#22]
Hello I got this error when I tried to run MORESANE: 

File "/usr/lib/python2.7/dist-packages/pymoresane/main.py", line 4, in <module>
    import pymoresane.iuwt as iuwt
  File "/usr/lib/python2.7/dist-packages/pymoresane/iuwt.py", line 9, in <module>
    import pycuda.autoinit
  File "/usr/lib/python2.7/dist-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
Error: cuInit failed: unknown error

> /usr/lib/python2.7/dist-packages/pycuda/autoinit.py(5)<module>()
-> cuda.init()

Would you know how this issue can be solved ? 
Thank you, 
Rita

**Comment by o-smirnov** [comment]
Looks like an issue with your GPU or CUDA setup rather than PyMORESANE itself. Try the ``nvidia-smi`` command, what does that say?

**Comment by rammanouil** [comment]
Hello Oleg, 
Thank you for your reply. 
The nvidia-smi gave the following message: NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
So basically I need to update my NVIDIA driver to enable the CUDA programming to work correctly ? 
Rita

**Comment by o-smirnov** [comment]
Yes, exactly.

**Comment by cyriltasse** [comment]
humm @rammanouil is running ubuntu inside a VM (on a mac). Maybe that creates the issue...

**Comment by o-smirnov** [comment]
Ah so there's no GPU? In this case just remove the cuda/pycuda packages entirely...

**Comment by JSKenyon** [comment]
@rammanouil This should be fixed now. Would you mind reinstalling from source and trying again?

**Comment by rammanouil** [comment]
Yes sure, I will. Thank you for fixing the issue.
