### ISSUE TITLE
ignore CUDA errors if GPU is disabled from the command line

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/PyMORESANE#23]
If GPU mode is explicitly disabled form the command line, we shouldn't attempt to import pycuda at all. I think at present it's always imported anyway, so people with broken (for whatever reason) CUDA setups don't have the option of falling back to CPU mode (see e.g. #22) .

**Comment by cyriltasse** [comment]
Yeah - I completely agree. The behaviour should be contrary even. Use it when specified. Cos in DDFacet we use Moresane inside SSD - really no need for GPU here since the images to be deconvolved are really tiny. Sill `PyMoresane` prints a pretty ugly error message telling that there is no GPU....

**Comment by JSKenyon** [comment]
Is this purely cosmetic? Looking at the code, the imports are in try statements, so failed imports shouldn't stop it from running in CPU mode.

**Comment by JSKenyon** [comment]
Bearing in mind that GPU functionality has to be turned on with something like -aog.

**Comment by cyriltasse** [comment]
@JSKenyon on my side - yeah cosmetic. :) But not for @rammanouil, where she simply cannot use `PyMoresane`, see issue#22

**Comment by o-smirnov** [comment]
> Looking at the code, the imports are in try statements, so failed imports shouldn't stop it from running in CPU mode.

That's the right idea. But, I'm guessing there's a try statement missing somewhere, because I can't even get ``--help``:
```
$ runsane --help
Traceback (most recent call last):
  File "/usr/bin/runsane", line 3, in <module>
    from pymoresane.main import main
  File "/home/oms/PyMORESANE/pymoresane/main.py", line 4, in <module>
    import pymoresane.iuwt as iuwt
  File "/home/oms/PyMORESANE/pymoresane/iuwt.py", line 9, in <module>
    import pycuda.autoinit
  File "/usr/lib/python2.7/dist-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.RuntimeError: cuInit failed: no CUDA-capable device is detected
```
This is on ``jake``, who needs a reboot for CUDA to work again.

**Comment by JSKenyon** [comment]
That seems peculiar. The line is question is [here](https://github.com/ratt-ru/PyMORESANE/blob/b67a2530e45c44f75237d5fde11061e2416fb842/pymoresane/iuwt.py#L9). This suggests that pycuda itself isn't handing the exception up to the try statement properly and this is premature termination.

**Comment by o-smirnov** [comment]
It's simpler than that -- the except clause only catches ImportErrors, while CUDA is throwing a RuntimeError. Probably better to catch a generic Exception.

**Comment by JSKenyon** [comment]
Hah. This is why I cannot be trusted to debug code written by old me.
