### ISSUE TITLE
main.py broken

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/PyMORESANE#5]
I get this error when I run `PyMORESANE/pymoresane/bin/runsane --help`

```
  File "bin/runsane", line 3, in <module>
    from pymoresane.main import main
ImportError: No module named pymoresane.main
```

**Comment by gijzelaerr** [comment]
you need to be inside **PyMORESANE** (current directory is implicitly added to your python path) or add the **PyMORESANE** folder to your `PYTHONPATH`

**Comment by o-smirnov** [comment]
Shouldn't it install itself somewhere in the PYTHONPATH?

**Comment by gijzelaerr** [comment]
well, in some cases you may want to run it uninstalled. 

BTW guys, did you know about `python setup.py develop`. That way you install it in development mode, which means it is installed but not copied, it is symlinked to your source checkout and changes become effective immediately.

**Comment by cyriltasse** [comment]
Why not setting a system like in LofarSys to properly source stuff. Like you do "use <packagename>" to set up the proper PATH, PYTHONPATH, LD_LIBRARY_PATH etc?... I find it very useful not to mix up things (stable with delevelopment, etc).

**Comment by gijzelaerr** [comment]
if you want you can set that up yourself, please lets not go the LOFAR/CASA way where we dictate how people should do stuff. Using the standard Python way is flexible enough that everybody can do whatever (s)he prefers.
