### ISSUE TITLE
Weird results with masking

### ISSUE THREAD

**Issue by aroffringa** [ratt-ru/PyMORESANE#7]
I'm testing how much flux MORESANE recovers in diffuse sources. I'm running it on this dirty image:

![dirty](https://cloud.githubusercontent.com/assets/11645549/7085791/8dae87ce-df7a-11e4-892a-f278ea65d715.png)

I provide a mask which is a square around the centre source; the other source is not in the mask. The mask is much larger than the source. After two iterations in WSClean, this is the final result:

![restored](https://cloud.githubusercontent.com/assets/11645549/7085808/b9b8197a-df7a-11e4-9747-f17499d8edd6.png)

And this is the model:

![model](https://cloud.githubusercontent.com/assets/11645549/7085818/cd356c6e-df7a-11e4-91e0-953a303d308a.png)

The model contains an arteficial line, which is placed at the boundary of the selected square in the mask. The images are 1536 x 1536, so not 2^something, but I thought this should be OK now.

**Comment by JSKenyon** [comment]
It looks to me as though the mask is not quite over the source. Could you
try multiplying the mask with the dirty image and confirming that no
portion of the source is being cut off? That can cause those weird edge
effects.

**Comment by aroffringa** [comment]
The line is the top of the selected square; the mask covers the source. Here is an image showing dirty times mask:

![dirty-times-mask](https://cloud.githubusercontent.com/assets/11645549/7085928/d14ae7ce-df7b-11e4-92c9-df04fa9a2b83.png)

**Comment by JSKenyon** [comment]
Hmmm, that is odd. The power of 2 thing shouldn't be an issue. So I am not
sure what would be causing this. Perhaps adjust the sigma level up a bit
and try again - might be that it goes too deep befor the first major cycle.

**Comment by aroffringa** [comment]
I've uploaded the files so you can debug it:
http://www.astro.rug.nl/~offringa/Moresane/mask-1536px.fits
http://www.astro.rug.nl/~offringa/Moresane/moresane-briggs0-dirty.fits
http://www.astro.rug.nl/~offringa/Moresane/moresane-briggs0-psf.fits

**Comment by aroffringa** [comment]
Hmm I rerun it with a single iteration and it seems to do something weird to the source :-/ Maybe the line is only in the second iteration, but then something is NQR in the first iteration

**Comment by JSKenyon** [comment]
Alright, I will take a look. May take me a few days - currently about to go
to my graduation ceremony. ☺

**Comment by aroffringa** [comment]
Enjoy :)

**Comment by chiaraf** [comment]
Hi! Congratulations Jon! :)
I can and would like to help with the tests, but I need to discuss with you before starting. May we have a chat one of these days?

**Comment by JSKenyon** [comment]
@aroffringa, I have run some tests of my own. Still trying to find the bug, but it seems to be something to do with the masking. In the mean time, try running with the following optional parameters and no mask:

-sbr 64 -tol 0.95
           OR
-sbr 128 -tol 0.95

Both will give better, though not perfect results. This should allow your major cycles to work correctly and hopefully prevent that bar from forming. Also, with such a small subregion it will take a few seconds at most.

**Comment by JSKenyon** [comment]
Ok, further progress made. Finally figured out why I was getting horrific answers - the mask contains 255's rather than 1's , and I was not forcing normalisation. 

As for the line, that would be one of the foreseeable consequences of the masking. The low scale wavelets are well correlated around the edges of the mask. One way of combating this may be to taper the edges of the mask rather than making it a simple binary mask. This should already work if you provide a tapered mask. I will look at tapering the mask internally, though it may be complicated.

**Comment by JSKenyon** [comment]
Tried it myself with a tapered mask - the edge nonsense disappeared. My results are not perfect - due to the fact that there are sources in the field which are not deconvolved, there are many artefacts corresponding to the PSF side-lobes of those sources.

**Comment by aroffringa** [comment]
Hmm yes sorry, I noticed the '255' vs '1's problem. The 255 mask is made by Gimp :-P, but WSClean will always hand a mask with '1's to Moresane, so that's not really a problem.

Good to hear that you have a solution for the problem. I don't really get why Moresane is putting a bar in the image though; shouldn't an abrupt ending of 'noise' do nothing? Or is the noise not really noiselike? Tapering a mask is not really compatible with how astronomers currently work... E.g. one may use a mask created by a source detector such a PyBDSM, which also has sharp edges. And how smooth a taper should it be? I think it would make sense when PyMORESANE applies an adequate taper to the mask, is that possible?

**Comment by chiaraf** [comment]
Hi. Just to know: how was the result of deconvolution without applying any mask?

**Comment by chiaraf** [comment]
Sorry, I closed by mistake.

**Comment by JSKenyon** [comment]
@aroffringa, I have figured out a way to taper the filters relatively easily. Is this still a desirable feature?

I will add it if you think it will be useful.

**Comment by JSKenyon** [comment]
By filters, I mean masks.

**Comment by aroffringa** [comment]
Hi @JSKenyon , well I've actually been working on a new deconvolution technique (in C++) that includes similar steps as Moresane (using IUWT as basis functions and a similar solve using the conjugate gradient method). This was mainly because I need to deconvolve including frequency and polarization info during making the models. I solve it there by just only selecting peaks that are in the mask. After the subsequent floodfill, pixels not in the mask are again unmasked, and in practice this seems to work (although I haven't tested it thoroughly yet). I also integrated the major step right into the deconvolution algorithm, and stop when any of the scales' peak has decreased to the mgain threshold. If you think that tapering the filters would be a better way to do it, I'm keen on seeing a demonstration...

But all in all, I am not so much interested in Moresane anymore, although it was a great reference to have for me (and it was PyMoresane that convinced me that there are compressed sensing methods that actually work ;)). I wish I could get the GPU version to work... My C++ version is still not super fast, so a GPU version that includes frequency+polarization awareness would still be very interesting... For if you get bored :P.

**Comment by JSKenyon** [comment]
Hehe, fair enough. Glad that you have seen that there is some merit to some of these techniques. Not sure I will get bored with my PhD any time soon, though I would be interested to see some results from the algorithm you have devised. And I believe that your technique of only selecting peaks in the mask will work brilliantly. :-) I will go ahead and close this for now, but will keep it in mind. The latest release should have a working GPU implementation provided all the dependencies are installed, if you decide you need it.
