### ISSUE TITLE
Outname required even if names of output images are specified. 

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/PyMORESANE#8]
The `outputaname` argument is still required even if I specify the `--residualname, --modelname, --restoredname` options. Would it be better to raise to a `too few arguments` error if `outputname` is not specified AND at least one of the output image names are not specified?

**Comment by JSKenyon** [comment]
I can take a look at this, but probably won't get to it till next week. Can
you fool it for now?

**Comment by sphemakh** [comment]
Sure, I don't need this now. Just reporting it :)

**Comment by JSKenyon** [comment]
Fixed in latest release. Will complain if the positional argument is omitted without specifying the individual names.
